# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\"x\n\rSensorRequest\x12\x10\n\x08\x64uration\x18\x01 \x01(\x01\x12\n\n\x02x0\x18\x02 \x01(\x01\x12\n\n\x02y0\x18\x03 \x01(\x01\x12\x12\n\ncomplexity\x18\x04 \x01(\x05\x12\n\n\x02xf\x18\x05 \x03(\x01\x12\n\n\x02yf\x18\x06 \x03(\x01\x12\x11\n\tsignature\x18\x07 \x01(\t\"`\n\x0eSensorResponse\x12\x13\n\x0bsensor_data\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x11\n\ttraceback\x18\x03 \x01(\t\x12\x17\n\x0f\x63ontroller_dump\x18\x04 \x01(\t2V\n\rSensorService\x12\x45\n\x12GenerateSensorData\x12\x15.sensor.SensorRequest\x1a\x16.sensor.SensorResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORREQUEST']._serialized_start=24
  _globals['_SENSORREQUEST']._serialized_end=144
  _globals['_SENSORRESPONSE']._serialized_start=146
  _globals['_SENSORRESPONSE']._serialized_end=242
  _globals['_SENSORSERVICE']._serialized_start=244
  _globals['_SENSORSERVICE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
